### ISSUE TITLE
I want to create Footer

### ISSUE THREAD

**Issue by je-ta** [borkweb/bootstrap-mediawiki#84]
I can not create a footer.
I create 「Bootstrap:Footer」page but I get an error.
It is in the log.
```
Stack trace:
#0 /Applications/MAMP/htdocs/mediawiki/skins/bootstrap-mediawiki/BootstrapMediaWiki.skin.php(244): BootstrapMediaWikiTemplate->includePage('Bootstrap:Foote...')
#1 /Applications/MAMP/htdocs/mediawiki/includes/skins/SkinTemplate.php(251): BootstrapMediaWikiTemplate->execute()
#2 /Applications/MAMP/htdocs/mediawiki/includes/OutputPage.php(2441): SkinTemplate->outputPage()
#3 /Applications/MAMP/htdocs/mediawiki/includes/exception/MWExceptionRenderer.php(186): OutputPage->output()
#4 /Applications/MAMP/htdocs/mediawiki/includes/exception/MWExceptionRenderer.php(55): MWExceptionRenderer::reportHTML(Object(Error))
#5 /Applications/MAMP/htdocs/mediawiki/includes/exception/MWExceptionHandler.php(75): MWExceptionRenderer::output(Object(Error), 2)
#6 /Applications/MAMP/htdocs/mediawiki/includes/exception/MWExceptionHandler.php(130): MWExceptionHandl in /Applications/MAMP/htdocs/mediawiki/skins/bootstrap-mediawiki/BootstrapMediaWiki.skin.php on line 482
```

The content of the footer is the same as the sample.
```
<div class="row">
	<div class="col-md-6">
		=== Stuff ===
		* [[Link to some place]]
		* [[Another link]]
	</div>
	<div class="col-md-6">
		=== More Stuff ===
		* [http://external.resource.org Go here]
	</div>
</div>
```
「Bootstrap:Subnav」 is also an error.
help me Please.

**Comment by Tumeden** [comment]
Also get an error.. 


[7a4f218c79d0638255a57868] /wiki/index.php/Bootstrap:Footer Error from line 482 of /var/www/html/wiki/skins/bootstrap-mediawiki/BootstrapMediaWiki.skin.php: Call to undefined method Article::getRawText()

Backtrace:

#0 /var/www/html/wiki/skins/bootstrap-mediawiki/BootstrapMediaWiki.skin.php(244): BootstrapMediaWikiTemplate->includePage(string)
#1 /var/www/html/wiki/includes/skins/SkinTemplate.php(251): BootstrapMediaWikiTemplate->execute()
#2 /var/www/html/wiki/includes/OutputPage.php(2441): SkinTemplate->outputPage()
#3 /var/www/html/wiki/includes/MediaWiki.php(869): OutputPage->output(boolean)
#4 /var/www/html/wiki/includes/MediaWiki.php(881): MediaWiki->{closure}()
#5 /var/www/html/wiki/includes/MediaWiki.php(523): MediaWiki->main()
#6 /var/www/html/wiki/index.php(43): MediaWiki->run()
#7 {main}

**Comment by soaperz** [comment]
Exactly the same for me....

same line error in the same file

**Comment by hspencer** [comment]
Yep. The same persistent problem over here...

**Comment by musicbanglatv** [comment]
Creat footer
